server:
  port: 8088
spring:
  application:
    name: sol-platform-service
  jackson:
    time-zone: UTC
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/currency?currentSchema=dev
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    url: jdbc:postgresql://localhost:5432/currency
    schemas: dev
    user: postgres
    password: postgres
    baseline-on-migrate: true
    locations: classpath:db/migration
logging:
  level:
    feign: DEBUG